# Generated by Django 4.0.3 on 2022-11-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arithmeticmodel',
            options={'ordering': ('-x',)},
        ),
    ]
