# Generated by Django 4.0.3 on 2022-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_arithmeticmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arithmeticmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='arithmeticmodel',
            name='operation_type',
            field=models.CharField(max_length=255),
        ),
    ]
