# Generated by Django 4.0.3 on 2022-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_arithmeticmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arithmeticmodel',
            name='operation_type',
            field=models.CharField(choices=[('addition', 'Addition'), ('multiplication', 'Multiplication'), ('subtraction', 'Subtraction')], max_length=255),
        ),
    ]
